### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by alanban** [humiaozuzu/wechat-explorer#12]
`DB path /Users/bansen/Documents/weixin/com.tencent.xin/Documents/**********************/DB/MM.sqlite
Traceback (most recent call last):
  File "/usr/local/bin/wexp", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/we/run.py", line 94, in main
    exporter = HTMLExporter(args.path, args.user_id, args.chatroom_id, args.start_at, args.end_at)
  File "/Library/Python/2.7/site-packages/we/contrib/html_exporter.py", line 15, in __init__
    self.records = self.wechat.get_chatroom_records(chatroom_id, start_at, end_at)
  File "/Library/Python/2.7/site-packages/we/wechat.py", line 167, in get_chatroom_records
    user_id, msg = row[4].split(':\n', 1)
ValueError: need more than 1 value to unpack`

**Comment by alanban** [comment]
> DB path /Users/bansen/Documents/weixin/com.tencent.xin/Documents/07ea6f2d7f8d5ef6c804fbbb1b462776/DB/MM.sqlite
Traceback (most recent call last):
  File "/usr/local/bin/wexp", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/we/run.py", line 94, in main
    exporter = HTMLExporter(args.path, args.user_id, args.chatroom_id, args.start_at, args.end_at)
  File "/Library/Python/2.7/site-packages/we/contrib/html_exporter.py", line 15, in __init__
    self.records = self.wechat.get_chatroom_records(chatroom_id, start_at, end_at)
  File "/Library/Python/2.7/site-packages/we/wechat.py", line 167, in get_chatroom_records
    user_id, msg = row[4].split(':\n', 1)
ValueError: need more than 1 value to unpack
