### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: wechat.html

### ISSUE THREAD

**Issue by xiaohuanshu** [humiaozuzu/wechat-explorer#5]
我用pip安装的，执行export_chatroom_records后出现错误。

DB path /Users/xiaohuanshu/Desktop/untitled folder/untitled folder/com.tencent.xin/Documents/f5bc0a899a092ddabef893bab12c0411/DB/MM.sqlite
DB path /Users/xiaohuanshu/Desktop/untitled folder/untitled folder/com.tencent.xin/Documents/f5bc0a899a092ddabef893bab12c0411/session/session.db
Bin path /Users/xiaohuanshu/Desktop/untitled folder/untitled folder/com.tencent.xin/Documents/f5bc0a899a092ddabef893bab12c0411/session/data/65/2f18225d972d895b4771ed9973b6ce
Traceback (most recent call last):
  File "/usr/local/bin/wexp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/we/run.py", line 95, in main
    exporter.export(args.export_path)
  File "/usr/local/lib/python2.7/site-packages/we/contrib/html_exporter.py", line 27, in export
    template = env.get_template('wechat.html')
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: wechat.html

**Comment by kswOok** [comment]
我也遇到了 这个问题

**Comment by oimken** [comment]
same here。。

**Comment by jianjin** [comment]
same here
