### ISSUE TITLE
unable to open database

### ISSUE THREAD

**Issue by yiwangwuqian** [humiaozuzu/wechat-explorer#9]
DB path /Users/xxx/Desktop/phone_back_up/com.tencent.xin/Documents/159b9e4ffb99789d7ecf7d0da8ea713c/DB/MM.sqlite
Traceback (most recent call last):
  File "/Users/xxx/Documents/FlaskProject/firstproject/venv/bin/wexp", line 11, in <module>
    sys.exit(main())
  File "/Users/xxx/Documents/FlaskProject/firstproject/venv/lib/python2.7/site-packages/we/run.py", line 58, in main
    friends = wechat.get_chatrooms()
  File "/Users/xxx/Documents/FlaskProject/firstproject/venv/lib/python2.7/site-packages/we/wechat.py", line 103, in get_chatrooms
    conn = sqlite3.connect(chat_db)
sqlite3.OperationalError: unable to open database file

**Comment by cherepo** [comment]
同样问题

**Comment by eliiik** [comment]
无法打开数据库 +1

**Comment by JiaWang-SZ** [comment]
无法打开数据库 +1

**Comment by bless66** [comment]
同样问题

**Comment by alejandrocca** [comment]
+2
